// Mapeamento player_class -> nome da classe no Grand Fantasia, fornecido pelo time
// do jogo. Usado pelo Hall da Fama para exibir o nome legivel da classe.
const CLASS_NAMES_BY_ID: Record<number, string> = {
  0: "Novato",
  1: "Lutador",
  2: "Guerreiro",
  3: "Berserker",
  4: "Paladino",
  5: "Caçador",
  6: "Arqueiro",
  7: "Ranger",
  8: "Assassino",
  9: "Acólito",
  10: "Sacerdote",
  11: "Clérigo",
  12: "Sábio",
  13: "Bruxo",
  14: "Mago",
  15: "Feiticeiro",
  16: "Necromante",
  17: "Titã",
  18: "Templário",
  19: "Franco Atirador",
  20: "Sicário Sombrio",
  21: "Profeta",
  22: "Místico",
  23: "Arquimago",
  24: "Demonólogo",
  25: "Maquinista Aprendiz",
  26: "Maquinista",
  27: "Agressor",
  28: "Demolidor",
  29: "Prime",
  30: "Optimus",
  31: "Optimus",
  32: "Cavaleiro da Morte",
  33: "Cavaleiro Real",
  34: "Mercenário",
  35: "Ninja",
  36: "Mensageiro Divino",
  37: "Xamã",
  38: "Arcano",
  39: "Emissário dos Mortos",
  40: "Destruidor",
  41: "Cavaleiro Sagrado",
  42: "Predador",
  43: "Shinobi",
  44: "Arcanjo",
  45: "Druida",
  46: "Bruxo",
  47: "Shinigami",
  48: "Megatron",
  49: "Galvatron",
  50: "Ômega",
  51: "Titã Celeste",
  52: "Viajante",
  53: "Nômade",
  54: "Espadachim",
  55: "Ilusionista",
  56: "Samurai",
  57: "Áugure",
  58: "Ronin",
  59: "Óraculo",
  60: "Mestre Dimensional",
  61: "Cronos"
};

const UNKNOWN_CLASS_NAME = "Desconhecido";

export function getClassName(playerClass: number) {
  return CLASS_NAMES_BY_ID[playerClass] ?? UNKNOWN_CLASS_NAME;
}
